n = input('Digite um valor: ')
m = float(input('Digite outro valor: '))
p = bool(input('Digite outro valor: '))
q = str(input('Digite algo: '))
w = int(input('Digite outro valor: '))
print(n)
print(m)
print(p)
print(q)
print(w)
print(type(n))
print(type(m))
print(type(p))
print(type(q))
print(type(w))
print(q.isnumeric())
#(isnumeric) verifica se digitou um número na string, se sim responde 'true' porque da pra converter para número.
