matriz = [[], [], []]
n1 = int(input('Digite um valor para a matriz [0, 0]: '))
n2 = int(input('Digite um valor para a matriz [0, 1]: '))
n3 = int(input('Digite um valor para a matriz [0, 2]: '))
n4 = int(input('Digite um valor para a matriz [1, 0]: '))
n5 = int(input('Digite um valor para a matriz [1, 1]: '))
n6 = int(input('Digite um valor para a matriz [1, 2]: '))
n7 = int(input('Digite um valor para a matriz [2, 0]: '))
n8 = int(input('Digite um valor para a matriz [2, 1]: '))
n9 = int(input('Digite um valor para a matriz [2, 2]: '))
matriz[0].append(n1)
matriz[0].append(n2)
matriz[0].append(n3)
matriz[1].append(n4)
matriz[1].append(n5)
matriz[1].append(n6)
matriz[2].append(n7)
matriz[2].append(n8)
matriz[2].append(n9)
print(f'[ {matriz[0][0]} ]', end='')
print(f'[ {matriz[0][1]} ]', end='')
print(f'[ {matriz[0][2]} ]', end='')
print()
print(f'[ {matriz[1][0]} ]', end='')
print(f'[ {matriz[1][1]} ]', end='')
print(f'[ {matriz[1][2]} ]', end='')
print()
print(f'[ {matriz[2][0]} ]', end='')
print(f'[ {matriz[2][1]} ]', end='')
print(f'[ {matriz[2][2]} ]', end='')
